/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package danielreyes_lab5p2;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;
import javax.swing.tree.TreeModel;

/**
 *
 * @author alema
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupmenutree = new javax.swing.JPopupMenu();
        menuitemmodificar = new javax.swing.JMenuItem();
        menuitemeliminar = new javax.swing.JMenuItem();
        menuitemlistar = new javax.swing.JMenuItem();
        popupmenuuniverso = new javax.swing.JPopupMenu();
        itemlistar = new javax.swing.JMenuItem();
        frameagregar = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textfieldnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textfieldpoder = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textfielddebilidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboboxu = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        buttoncrear = new javax.swing.JButton();
        spinnerfuerza = new javax.swing.JSpinner();
        spinnerfisica = new javax.swing.JSpinner();
        spinnermental = new javax.swing.JSpinner();
        spinnerhp = new javax.swing.JSpinner();
        framelistado = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtree = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlist = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        textfielimprimidor = new javax.swing.JTextField();
        framemodificar = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textfieldnombre1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        textfieldpoder1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        textfielddebilidad1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        comboboxu1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        buttoncrear1 = new javax.swing.JButton();
        spinnerfuerza1 = new javax.swing.JSpinner();
        spinnerfisica1 = new javax.swing.JSpinner();
        spinnermental1 = new javax.swing.JSpinner();
        spinnerhp1 = new javax.swing.JSpinner();
        framebatalla = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        comboboxu2 = new javax.swing.JComboBox<>();
        comboboxu3 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlist3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlist2 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        frameSimulacion = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textareasimulacion = new javax.swing.JTextArea();
        textfieldindicadorturnos = new javax.swing.JTextField();
        buttonFuerza = new javax.swing.JButton();
        buttonFisico = new javax.swing.JButton();
        buttonMental = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        panelmenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button_agregar = new javax.swing.JButton();
        button_batalla = new javax.swing.JButton();
        button_listado = new javax.swing.JButton();
        button_salir = new javax.swing.JButton();

        menuitemmodificar.setText("Modificar el personaje");
        menuitemmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemmodificarActionPerformed(evt);
            }
        });
        popupmenutree.add(menuitemmodificar);

        menuitemeliminar.setText("Eliminar el personaje");
        menuitemeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemeliminarActionPerformed(evt);
            }
        });
        popupmenutree.add(menuitemeliminar);

        menuitemlistar.setText("Listar ");
        menuitemlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitemlistarActionPerformed(evt);
            }
        });
        popupmenutree.add(menuitemlistar);

        itemlistar.setText("Listar nombres del universo");
        itemlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemlistarActionPerformed(evt);
            }
        });
        popupmenuuniverso.add(itemlistar);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 3, 48)); // NOI18N
        jLabel2.setText("Agregar");

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel4.setText("Poder");

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel5.setText("Debilidad");

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel6.setText("Universo");

        comboboxu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Capcom", "Mortal Kombat" }));

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel7.setText("Fuerza");

        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel8.setText("Físico");

        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel9.setText("Mental");

        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel10.setText("HP");

        buttoncrear.setBackground(new java.awt.Color(0, 0, 0));
        buttoncrear.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        buttoncrear.setForeground(new java.awt.Color(255, 255, 255));
        buttoncrear.setText("Crear");
        buttoncrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttoncrearMouseClicked(evt);
            }
        });

        spinnerfuerza.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spinnerfisica.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spinnermental.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spinnerhp.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(287, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboboxu, javax.swing.GroupLayout.Alignment.LEADING, 0, 330, Short.MAX_VALUE)
                        .addComponent(textfielddebilidad, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textfieldnombre, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textfieldpoder, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttoncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spinnerhp, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spinnermental, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spinnerfisica, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spinnerfuerza, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerfuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldpoder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerfisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfielddebilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnermental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerhp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(buttoncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout frameagregarLayout = new javax.swing.GroupLayout(frameagregar.getContentPane());
        frameagregar.getContentPane().setLayout(frameagregarLayout);
        frameagregarLayout.setHorizontalGroup(
            frameagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameagregarLayout.setVerticalGroup(
            frameagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setFont(new java.awt.Font("Lucida Handwriting", 3, 48)); // NOI18N
        jLabel11.setText("Listado");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personajes");
        jtree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jtree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtreeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtree);

        jlist.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jlist);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        textfielimprimidor.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfielimprimidor, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfielimprimidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout framelistadoLayout = new javax.swing.GroupLayout(framelistado.getContentPane());
        framelistado.getContentPane().setLayout(framelistadoLayout);
        framelistadoLayout.setHorizontalGroup(
            framelistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        framelistadoLayout.setVerticalGroup(
            framelistadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel12.setFont(new java.awt.Font("Lucida Handwriting", 3, 48)); // NOI18N
        jLabel12.setText("Modificar");

        jLabel13.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel13.setText("Nombre");

        jLabel14.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel14.setText("Poder");

        jLabel15.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel15.setText("Debilidad");

        jLabel16.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel16.setText("Universo");

        comboboxu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Capcom", "Mortal Kombat" }));

        jLabel17.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel17.setText("Fuerza");

        jLabel18.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel18.setText("Física");

        jLabel19.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel19.setText("Mental");

        jLabel20.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel20.setText("HP");

        buttoncrear1.setBackground(new java.awt.Color(0, 0, 0));
        buttoncrear1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        buttoncrear1.setForeground(new java.awt.Color(255, 255, 255));
        buttoncrear1.setText("Modificar");
        buttoncrear1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttoncrear1MouseClicked(evt);
            }
        });

        spinnerfuerza1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spinnerfisica1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spinnermental1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spinnerhp1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboboxu1, javax.swing.GroupLayout.Alignment.LEADING, 0, 330, Short.MAX_VALUE)
                        .addComponent(textfielddebilidad1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textfieldnombre1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textfieldpoder1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttoncrear1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spinnerhp1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spinnermental1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spinnerfisica1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spinnerfuerza1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(211, 211, 211))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerfuerza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldpoder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerfisica1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfielddebilidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnermental1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerhp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(buttoncrear1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout framemodificarLayout = new javax.swing.GroupLayout(framemodificar.getContentPane());
        framemodificar.getContentPane().setLayout(framemodificarLayout);
        framemodificarLayout.setHorizontalGroup(
            framemodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        framemodificarLayout.setVerticalGroup(
            framemodificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        comboboxu2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Capcom", "Mortal Kombat" }));
        comboboxu2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboboxu2ItemStateChanged(evt);
            }
        });

        comboboxu3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Capcom", "Mortal Kombat" }));
        comboboxu3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboboxu3ItemStateChanged(evt);
            }
        });

        jlist3.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jlist3);

        jlist2.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jlist2);

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setText("Batalla");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setText("Volver");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboboxu2, 0, 330, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(62, 62, 62)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(comboboxu3, 0, 330, Short.MAX_VALUE))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboboxu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout framebatallaLayout = new javax.swing.GroupLayout(framebatalla.getContentPane());
        framebatalla.getContentPane().setLayout(framebatallaLayout);
        framebatallaLayout.setHorizontalGroup(
            framebatallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        framebatallaLayout.setVerticalGroup(
            framebatallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        textareasimulacion.setEditable(false);
        textareasimulacion.setColumns(20);
        textareasimulacion.setRows(5);
        jScrollPane5.setViewportView(textareasimulacion);

        textfieldindicadorturnos.setEditable(false);

        buttonFuerza.setText("Fuerza");
        buttonFuerza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonFuerzaMouseClicked(evt);
            }
        });

        buttonFisico.setText("Física");
        buttonFisico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonFisicoMouseClicked(evt);
            }
        });

        buttonMental.setText("Mental");
        buttonMental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMentalMouseClicked(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 153, 102));
        jButton4.setText("X");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(textfieldindicadorturnos, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(buttonFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(buttonFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonMental, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(textfieldindicadorturnos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMental, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameSimulacionLayout = new javax.swing.GroupLayout(frameSimulacion.getContentPane());
        frameSimulacion.getContentPane().setLayout(frameSimulacionLayout);
        frameSimulacionLayout.setHorizontalGroup(
            frameSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameSimulacionLayout.setVerticalGroup(
            frameSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelmenu.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU");

        button_agregar.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        button_agregar.setText("Agregar Personaje");
        button_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_agregarMouseClicked(evt);
            }
        });

        button_batalla.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        button_batalla.setText("Simulación de Batalla");
        button_batalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_batallaMouseClicked(evt);
            }
        });

        button_listado.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        button_listado.setText("Listado de Personajes");
        button_listado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_listadoMouseClicked(evt);
            }
        });

        button_salir.setBackground(new java.awt.Color(255, 153, 153));
        button_salir.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        button_salir.setText("Salir");
        button_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_salirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelmenuLayout = new javax.swing.GroupLayout(panelmenu);
        panelmenu.setLayout(panelmenuLayout);
        panelmenuLayout.setHorizontalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelmenuLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addGroup(panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_listado, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_batalla, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(201, 201, 201))
        );
        panelmenuLayout.setVerticalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(button_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(button_listado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(button_batalla, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(button_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_agregarMouseClicked
        this.setVisible(false);
        frameagregar.pack();
        frameagregar.setLocationRelativeTo(this);
        frameagregar.setVisible(true);
        
    }//GEN-LAST:event_button_agregarMouseClicked

    private void buttoncrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttoncrearMouseClicked
        Personaje p;
        
        p = new Personaje(textfieldnombre.getText(), textfieldpoder.getText(), textfielddebilidad.getText(), comboboxu.getSelectedItem().toString(),((Integer)spinnerfuerza.getValue()) , ((Integer)spinnerfisica.getValue()), ((Integer)spinnermental.getValue()), ((Integer)spinnerhp.getValue()));
        listapersonajes.add(p);
        
        //agregar al tree
        DefaultTreeModel modelo = (DefaultTreeModel) jtree.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
        DefaultMutableTreeNode nodo_nombre = new DefaultMutableTreeNode(p);
        
        int cont = 0;
        for (int i = 0; i < root.getChildCount(); i++) {
            if(root.getChildAt(i).toString().equals(comboboxu.getSelectedItem().toString())){
                cont++;
               
            }
        }
        if (cont >0){
            for (int i = 0; i < root.getChildCount(); i++) {
                if(root.getChildAt(i).toString().equals(comboboxu.getSelectedItem().toString())){
                    ((DefaultMutableTreeNode)root.getChildAt(i)).add(nodo_nombre);
                    break;
                }
            }
            
        }else{
            DefaultMutableTreeNode nodo_universo = new DefaultMutableTreeNode(comboboxu.getSelectedItem().toString());
            nodo_universo.add(nodo_nombre);
            root.add(nodo_universo);
        }
        modelo.reload();
        
        
        //reset espacios
        textfieldnombre.setText("");
        textfieldpoder.setText("");
        textfielddebilidad.setText("");
        comboboxu.setSelectedIndex(0);
        spinnerfuerza.setValue(0);
        spinnerfisica.setValue(0);
        spinnerhp.setValue(0);
        spinnermental.setValue(0);
        
        frameagregar.setVisible(false);
        this.pack();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
        
    }//GEN-LAST:event_buttoncrearMouseClicked

    private void button_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_salirMouseClicked
       System.exit(0);
    }//GEN-LAST:event_button_salirMouseClicked

    private void button_listadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_listadoMouseClicked
    this.setVisible(false);
    framelistado.pack();
    framelistado.setLocationRelativeTo(this);
    framelistado.setVisible(true);
    
    }//GEN-LAST:event_button_listadoMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        framelistado.setVisible(false);
        this.pack();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jtreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtreeMouseClicked
        jtree.setSelectionRow(jtree.getClosestRowForLocation(evt.getX(), evt.getY()));
        DefaultMutableTreeNode nodoactual = (DefaultMutableTreeNode)jtree.getSelectionPath().getLastPathComponent();
        nodo_actual = nodoactual;
        if(evt.getButton()== 3){
            
            if( nodoactual.getUserObject() instanceof Personaje ){
                
                popupmenutree.show(evt.getComponent(), evt.getX(), evt.getY());
                
            }else if (nodo_actual.getUserObject().equals("DC")||nodo_actual.getUserObject().equals("Marvel")||nodo_actual.getUserObject().equals("Capcom")||nodo_actual.getUserObject().equals("Mortal Kombat")){
                popupmenuuniverso.show(evt.getComponent(), evt.getX(), evt.getY());
            }
            
            
            
        }
    }//GEN-LAST:event_jtreeMouseClicked

    private void buttoncrear1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttoncrear1MouseClicked
        ((Personaje)nodo_actual.getUserObject()).setNombre(textfieldnombre1.getText());
        ((Personaje)nodo_actual.getUserObject()).setUniverso(comboboxu1.getSelectedItem().toString());
        ((Personaje)nodo_actual.getUserObject()).setPoder(textfieldpoder1.getText());
        ((Personaje)nodo_actual.getUserObject()).setDebilidad(textfielddebilidad1.getText());
        ((Personaje)nodo_actual.getUserObject()).setMental((int) spinnermental1.getValue());
        ((Personaje)nodo_actual.getUserObject()).setHp((int) spinnerhp1.getValue());
        ((Personaje)nodo_actual.getUserObject()).setFuerza((int) spinnerfuerza1.getValue());
        ((Personaje)nodo_actual.getUserObject()).setFisica((int) spinnerfisica1.getValue());
        
        framemodificar.setVisible(false);
        framelistado.pack();
        framelistado.setLocationRelativeTo(this);
        framelistado.setVisible(true);
    }//GEN-LAST:event_buttoncrear1MouseClicked

    private void menuitemmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemmodificarActionPerformed
        framelistado.setVisible(false);
        framemodificar.pack();
        framemodificar.setLocationRelativeTo(this);
        framemodificar.setVisible(true);
        Personaje p = (Personaje)nodo_actual.getUserObject();
        
        textfieldnombre1.setText(p.getNombre());
        textfieldpoder1.setText(p.getPoder());
        textfielddebilidad1.setText(p.getDebilidad());
        //Para el combobox
        int combo=3;
        if(p.getUniverso().equals("DC")){
            combo = 0;
        }else if(p.getUniverso().equals("Marvel")){
            combo = 1;
        }else if (p.getUniverso().equals("Capcom")){
            combo= 2;
        }
        comboboxu1.setSelectedIndex(combo);
        spinnerfuerza1.setValue(p.getFuerza());
        spinnerfisica1.setValue(p.getFisica());
        spinnerhp1.setValue(p.getHp());
        spinnermental1.setValue(p.getMental());
        
        
    }//GEN-LAST:event_menuitemmodificarActionPerformed

    private void menuitemeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemeliminarActionPerformed
        DefaultTreeModel modelo = (DefaultTreeModel) jtree.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) modelo.getRoot();
        if(nodo_actual.getParent().getChildCount()== 1){
            modelo.removeNodeFromParent(nodo_actual.getPreviousNode());
        }else{
            modelo.removeNodeFromParent(nodo_actual);
        }
        modelo.reload();
        
        
    }//GEN-LAST:event_menuitemeliminarActionPerformed

    private void menuitemlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemlistarActionPerformed
        DefaultListModel modelo = (DefaultListModel) jlist.getModel();
        Personaje p = (Personaje)nodo_actual.getUserObject();
        textfielimprimidor.setText("");
        modelo.removeAllElements();
        textfielimprimidor.setText(p.toString());
        
        modelo.addElement(p.toStringnombre());
        jlist.setModel(modelo);
    }//GEN-LAST:event_menuitemlistarActionPerformed

    private void itemlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemlistarActionPerformed
        textfielimprimidor.setText("");
        textfielimprimidor.setText(nodo_actual.toString());
        DefaultListModel modelo = (DefaultListModel) jlist.getModel();
        modelo.removeAllElements();
        Personaje p;
        if(nodo_actual.getUserObject().equals("DC")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("DC")){
                    p = listapersonajes.get(i);
                    modelo.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }else if(nodo_actual.getUserObject().equals("Marvel")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("Marvel")){
                    p = listapersonajes.get(i);
                    modelo.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }else if(nodo_actual.getUserObject().equals("Capcom")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("Capcom")){
                    p = listapersonajes.get(i);
                    modelo.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }else if(nodo_actual.getUserObject().equals("Mortal Kombat")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("Mortal Kombat")){
                    p = listapersonajes.get(i);
                    modelo.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }
        
        jlist.setModel(modelo);
    }//GEN-LAST:event_itemlistarActionPerformed

    private void button_batallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_batallaMouseClicked
        this.setVisible(false);
        framebatalla.pack();
        framebatalla.setLocationRelativeTo(this);
        framebatalla.setVisible(true);
        DefaultListModel modelo2 = (DefaultListModel) jlist2.getModel();
        modelo2.removeAllElements();
        DefaultListModel modelo3 = (DefaultListModel) jlist3.getModel();
        modelo3.removeAllElements();
        Personaje p;
        //primer combo box
        if(comboboxu2.getSelectedItem().equals("DC")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("DC")){
                    p = listapersonajes.get(i);
                    modelo2.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }else if(comboboxu2.getSelectedItem().equals("Marvel")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("Marvel")){
                    p = listapersonajes.get(i);
                    modelo2.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }else if(comboboxu2.getSelectedItem().equals("Capcom")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("Capcom")){
                    p = listapersonajes.get(i);
                    modelo2.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }else if(comboboxu2.getSelectedItem().equals("Mortal Kombat")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("Mortal Kombat")){
                    p = listapersonajes.get(i);
                    modelo2.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }
        //segundo combobox
        if(comboboxu3.getSelectedItem().equals("DC")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("DC")){
                    p = listapersonajes.get(i);
                    modelo3.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }else if(comboboxu3.getSelectedItem().equals("Marvel")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("Marvel")){
                    p = listapersonajes.get(i);
                    modelo3.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }else if(comboboxu3.getSelectedItem().equals("Capcom")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("Capcom")){
                    p = listapersonajes.get(i);
                    modelo3.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }else if(comboboxu3.getSelectedItem().equals("Mortal Kombat")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("Mortal Kombat")){
                    p = listapersonajes.get(i);
                    modelo3.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }
        
    }//GEN-LAST:event_button_batallaMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        framebatalla.setVisible(false);
        this.pack();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void comboboxu2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboboxu2ItemStateChanged
        Personaje p;
        DefaultListModel modelo2 = (DefaultListModel) jlist2.getModel();
        modelo2.removeAllElements();
        if(comboboxu2.getSelectedItem().equals("DC")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("DC")){
                    p = listapersonajes.get(i);
                    modelo2.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }else if(comboboxu2.getSelectedItem().equals("Marvel")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("Marvel")){
                    p = listapersonajes.get(i);
                    modelo2.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }else if(comboboxu2.getSelectedItem().equals("Capcom")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("Capcom")){
                    p = listapersonajes.get(i);
                    modelo2.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }else if(comboboxu2.getSelectedItem().equals("Mortal Kombat")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("Mortal Kombat")){
                    p = listapersonajes.get(i);
                    modelo2.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }
        jlist2.setModel(modelo2);
    }//GEN-LAST:event_comboboxu2ItemStateChanged

    private void comboboxu3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboboxu3ItemStateChanged
        DefaultListModel modelo3 = (DefaultListModel) jlist3.getModel();
        Personaje p;
        modelo3.removeAllElements();
        if(comboboxu3.getSelectedItem().equals("DC")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("DC")){
                    p = listapersonajes.get(i);
                    modelo3.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }else if(comboboxu3.getSelectedItem().equals("Marvel")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("Marvel")){
                    p = listapersonajes.get(i);
                    modelo3.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }else if(comboboxu3.getSelectedItem().equals("Capcom")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("Capcom")){
                    p = listapersonajes.get(i);
                    modelo3.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }else if(comboboxu3.getSelectedItem().equals("Mortal Kombat")){
            for (int i = 0; i < listapersonajes.size(); i++) {
                if(listapersonajes.get(i).getUniverso().equals("Mortal Kombat")){
                    p = listapersonajes.get(i);
                    modelo3.addElement(p + "-> "+ p.toStringnombre());
                }
            }
        }
        jlist3.setModel(modelo3);
    }//GEN-LAST:event_comboboxu3ItemStateChanged

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        frameSimulacion.setVisible(true);
        framebatalla.pack();
        framebatalla.setLocationRelativeTo(this);
        framebatalla.setVisible(true);
                
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        if(jlist2.isSelectionEmpty()== false && jlist3.isSelectionEmpty()== false){
            framebatalla.setVisible(false);
            frameSimulacion.pack();
            frameSimulacion.setLocationRelativeTo(this);
            frameSimulacion.setVisible(true);

            String jugador1 = jlist2.getSelectedValue();
            String jugador2 = jlist3.getSelectedValue();
            textfieldindicadorturnos.setText("Turno del jugador " + jugador1.split("-")[0]);
        }else{
            JOptionPane.showMessageDialog(frameSimulacion, "Debe seleccionar un personaje de cada ");
        }
        
        
        
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void buttonFuerzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFuerzaMouseClicked
        String area= "";
        if(textfieldindicadorturnos.getText().contains(jlist2.getSelectedValue().split("-")[0])){
            area+=  textareasimulacion.getText();
            textareasimulacion.setText(area +"\nEl jugador " + jlist2.getSelectedValue().split("-")[0]+ " ha subido sus puntos de vida" );
            textfieldindicadorturnos.setText("");
            textfieldindicadorturnos.setText("Turno del jugador "+jlist3.getSelectedValue().split("-")[0] );
        }else{
            area+=  textareasimulacion.getText();
            textareasimulacion.setText(area +"\nEl jugador " + jlist3.getSelectedValue().split("-")[0]+ " ha subido sus puntos de vida" );
            textfieldindicadorturnos.setText("");
            textfieldindicadorturnos.setText("Turno del jugador "+jlist2.getSelectedValue().split("-")[0] );
        }
        
    }//GEN-LAST:event_buttonFuerzaMouseClicked

    private void buttonFisicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFisicoMouseClicked
        String area= "";
        if(textfieldindicadorturnos.getText().contains(jlist2.getSelectedValue().split("-")[0])){
            area+=  textareasimulacion.getText();
            textareasimulacion.setText(area +"\nEl jugador ha usado su ataque fuerte" + jlist2.getSelectedValue().split("-")[0]+ " le ha quitado mucha vida a "+ jlist3.getSelectedValue().split("-")[0] );
            textfieldindicadorturnos.setText("");
            textfieldindicadorturnos.setText("Turno del jugador "+jlist3.getSelectedValue().split("-")[0] );
        }else{
            area+=  textareasimulacion.getText();
            textareasimulacion.setText(area +"\nEl jugador ha usado su ataque fuerte" + jlist2.getSelectedValue().split("-")[0]+ " le ha quitado mucha vida a "+ jlist3.getSelectedValue().split("-")[0] );
            textfieldindicadorturnos.setText("");
            textfieldindicadorturnos.setText("Turno del jugador "+jlist2.getSelectedValue().split("-")[0] );
        }
    }//GEN-LAST:event_buttonFisicoMouseClicked

    private void buttonMentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMentalMouseClicked
String area= "";
        if(textfieldindicadorturnos.getText().contains(jlist2.getSelectedValue().split("-")[0])){
            area+=  textareasimulacion.getText();
            textareasimulacion.setText(area +"\nEl jugador ha usado su ataque mental" + jlist2.getSelectedValue().split("-")[0]+ " le ha quitado vida a "+ jlist3.getSelectedValue().split("-")[0] );
            textfieldindicadorturnos.setText("");
            textfieldindicadorturnos.setText("Turno del jugador "+jlist3.getSelectedValue().split("-")[0] );
        }else{
            area+=  textareasimulacion.getText();
            textareasimulacion.setText(area +"\nEl jugador ha usado su ataque mental" + jlist2.getSelectedValue().split("-")[0]+ " le ha quitado vida a "+ jlist3.getSelectedValue().split("-")[0] );
            textfieldindicadorturnos.setText("");
            textfieldindicadorturnos.setText("Turno del jugador "+jlist2.getSelectedValue().split("-")[0] );
        }
    }//GEN-LAST:event_buttonMentalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFisico;
    private javax.swing.JButton buttonFuerza;
    private javax.swing.JButton buttonMental;
    private javax.swing.JButton button_agregar;
    private javax.swing.JButton button_batalla;
    private javax.swing.JButton button_listado;
    private javax.swing.JButton button_salir;
    private javax.swing.JButton buttoncrear;
    private javax.swing.JButton buttoncrear1;
    private javax.swing.JComboBox<String> comboboxu;
    private javax.swing.JComboBox<String> comboboxu1;
    private javax.swing.JComboBox<String> comboboxu2;
    private javax.swing.JComboBox<String> comboboxu3;
    private javax.swing.JFrame frameSimulacion;
    private javax.swing.JFrame frameagregar;
    private javax.swing.JFrame framebatalla;
    private javax.swing.JFrame framelistado;
    private javax.swing.JFrame framemodificar;
    private javax.swing.JMenuItem itemlistar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> jlist;
    private javax.swing.JList<String> jlist2;
    private javax.swing.JList<String> jlist3;
    private javax.swing.JTree jtree;
    private javax.swing.JMenuItem menuitemeliminar;
    private javax.swing.JMenuItem menuitemlistar;
    private javax.swing.JMenuItem menuitemmodificar;
    private javax.swing.JPanel panelmenu;
    private javax.swing.JPopupMenu popupmenutree;
    private javax.swing.JPopupMenu popupmenuuniverso;
    private javax.swing.JSpinner spinnerfisica;
    private javax.swing.JSpinner spinnerfisica1;
    private javax.swing.JSpinner spinnerfuerza;
    private javax.swing.JSpinner spinnerfuerza1;
    private javax.swing.JSpinner spinnerhp;
    private javax.swing.JSpinner spinnerhp1;
    private javax.swing.JSpinner spinnermental;
    private javax.swing.JSpinner spinnermental1;
    private javax.swing.JTextArea textareasimulacion;
    private javax.swing.JTextField textfielddebilidad;
    private javax.swing.JTextField textfielddebilidad1;
    private javax.swing.JTextField textfieldindicadorturnos;
    private javax.swing.JTextField textfieldnombre;
    private javax.swing.JTextField textfieldnombre1;
    private javax.swing.JTextField textfieldpoder;
    private javax.swing.JTextField textfieldpoder1;
    private javax.swing.JTextField textfielimprimidor;
    // End of variables declaration//GEN-END:variables
    ArrayList<Personaje> listapersonajes = new ArrayList();
    DefaultMutableTreeNode nodo_actual;



}
